### ISSUE TITLE
NullPointerException at create account without owner

### ISSUE THREAD

**Issue by M-Szymczyk** [M-Szymczyk/ProjektPortfel#1]
Po utworzeniu kona bez właściciela i wyświetleniu tego pojawia się NullPointerException.
proponuje sprawdzać to przy wyświetleniu i pytać, czy nie chce dodać właściciela.

**Comment by wolski0420** [comment]
Bug naprawiony. Nie robiłem tego jakoś arcypięknie bo uznałem że nie warto, ważniejsza będzie wersja z GUI bo konsolowej wersji i tak nikt nie będzie używać. Wszystkie zmiany są na branch'u "workspace". Wszczepiony jest też już algorytm odpowiedzialny za unikalność numerów kont bankowych. Dam pull request'a do mastera, żeby był widoczny postęp. Potem dodam kolejny issue z propozycją dalszej organizacji i pomysłu, można tam podyskutować.

**Comment by wolski0420** [comment]
Czemu in progress? Jest skończone xD
