### ISSUE TITLE
Znaleźć i naprawić błędy w readme 

### ISSUE THREAD

**Issue by M-Szymczyk** [M-Szymczyk/ProjektPortfel#2]
Na pewno są jakieś głupie błędy, które nie rzucają mi się w oczy xd

**Comment by wolski0420** [comment]
Znalezione, naprawione, ulepszone - dwa README w różnej wersji językowej, każde zawierające odnośniki do innych wersji językowych. Wszystko na branch'u workspace. 

P.S. odnośniki zawierają nazwę branch'a, jak dam pull request'a to po merge'u do mastera linki do wersji mogą nie działać, konieczna będzie aktualizacja linków po merge'u.
