### ISSUE TITLE
Rozdzielenie funkcjonalności silnika i fasady

### ISSUE THREAD

**Issue by M-Szymczyk** [M-Szymczyk/ProjektPortfel#20]
Wyciągnięcie wszystkich strumienie wejściowych i wyjściowych do klasy MoneyMenagerConsoleAPP w celu ulatwienia implementacji wersji okienkowej i na androida.

**Comment by wolski0420** [comment]
Część zrobiłem, pakiet data jest uporządkowany, silnik też, zostało wykonać co nie co w klasie odpowiadającej za wersję konsolową

**Comment by wolski0420** [comment]
Rozdzielenie zrobione. Zaraz puszczam commity i tworzę PR,  którego podczepię tutaj i pod inne 2 issues. Jak by się okazało że coś jeszcze trzeba zrobić w ramach rozdzielenia to przed akceptacją się zrobi i puści commita
