### ISSUE TITLE
Transakcje w kontach bankowych

### ISSUE THREAD

**Issue by wolski0420** [M-Szymczyk/ProjektPortfel#3]
Nie mam zielonego pojęcia kto miał to zrobić, ale wrzucam bo jest tam komentarz w kodzie

**Comment by M-Szymczyk** [comment]
W projekcie masz kartę transakcje, skoro nikt nie jest przypisany to chyba tego nie ustaliliśmy

**Comment by wolski0420** [comment]
A to tego nie widziałem. Chyba że dopiero dodałeś to ok
