### ISSUE TITLE
Propozycja organizacji

### ISSUE THREAD

**Issue by wolski0420** [M-Szymczyk/ProjektPortfel#7]
Najpierw code review dla mojego pull requesta, potem dokończyć całkowicie wersję konsolową, na którą składają się przede wszystkim 3 i 4 issue. Nad tym ostatnim gdzie przeniosłem z Maina komentarze uważam, że nie powinniśmy się teraz skupiać, ważne żeby apka miała podstawowe funkcjonalności. Zrobiłbym tak, że po skończeniu 3 i 4 issue wszystko na mastera, kończymy milestone i przerzucamy cały rezultat na nowego brancha, którego już nie będziemy tykać. Milestone z GUI będzie się opierał na tym co wcześniej zrobiliśmy, więc clone z mastera, ale pracujemy na innym branchu i po większych zmianach lub na sam koniec pull requestujemy na mastera i finalnie kończymy na dwóch branchach, jeden od jednego milestone'a, drugi od drugiego. To też dla nas jakaś opcja gdybyśmy potem chcieli po skończeniu tego projektu go forkować i coś tam robić sobie, mamy zawsze obydwie wersje i możemy pracować na dowolnej z nich, no i też gdyby się np komuś zachciało zmienić framework do GUI to rozwiązanie z oddzielnymi branchami na milestone'y jest tutaj całkiem przyzwoite.

Widziałem też jakieś namiastki swinga. Proponuję javafx, można się nieraz podenerwować że coś nie działa, ale i tak całkiem fajnie się w tym pisze. No i wolałbym pisac w czymś co ma wsparcie i się rozwija a nie uczyć się staroci xD. Jeżeli jednak czujesz się bardziej w swingu no to mogę próbować swoich sił, ale raczej będę tak robił, żeby za dużo w tym nie pisać xD. Co do FX to z importem problemu nie powinno być, bo już zależności w gradlu zrobiłem i intellij mi wykrywał FX'owe klasy także kodzik is ready for javafx

**Comment by M-Szymczyk** [comment]
yyy Jak chcesz robić takie propozycje to nie lepiej od razu je wrzucać do projektu?
Rób odniesienia do issue bo to dla mnie jest 4. issue xd

**Comment by wolski0420** [comment]
Imo lepiej najpierw przedyskutować niż odrazu robić issues i wrzucać do projektu

**Comment by M-Szymczyk** [comment]
Do zrobienia:
- [ ] code review dla mojego pull requesta,
- [ ] potem dokończyć całkowicie wersję konsolową, na którą składają się przede wszystkim #3  i #4  issue.

>  Nad tym ostatnim gdzie przeniosłem z Maina komentarze uważam, że nie powinniśmy się teraz skupiać, ważne żeby apka miała podstawowe funkcjonalności. Zrobiłbym tak, że po skończeniu 3 i 4 issue wszystko na mastera, kończymy milestone i przerzucamy cały rezultat na nowego brancha, którego już nie będziemy tykać.

Można zrobić jakieś realse co jest po prawej stronie jak wejdziesz w repo. Nie mam pojęcia jak to działa. Jeżli o nie wyjdzie to możemy zapisać ten stan na innym branchu  i dać mu odpowiednie uprawnienia żeby ktoś go nie usunął.

> Milestone z GUI będzie się opierał na tym co wcześniej zrobiliśmy, więc clone z mastera, ale pracujemy na innym branchu i po większych zmianach lub na sam koniec pull requestujemy na mastera i finalnie kończymy na dwóch branchach, jeden od jednego milestone'a, drugi od drugiego. To też dla nas jakaś opcja gdybyśmy potem chcieli po skończeniu tego projektu go forkować i coś tam robić sobie, mamy zawsze obydwie wersje i możemy pracować na dowolnej z nich, no i też gdyby się np komuś zachciało zmienić framework do GUI to rozwiązanie z oddzielnymi branchami na milestone'y jest tutaj całkiem przyzwoite.

Pomysł z dwoma takimi branchami jest spoko, ale i tak bym spróbował zrobić to co wyżej napisałem.
Co do GUI to możesz przygotować jakieś zadania do zrobienia później?

> Widziałem też jakieś namiastki swinga. Proponuję javafx, można się nieraz podenerwować że coś nie działa, ale i tak całkiem fajnie się w tym pisze. No i wolałbym pisac w czymś co ma wsparcie i się rozwija a nie uczyć się staroci xD. Jeżeli jednak czujesz się bardziej w swingu no to mogę próbować swoich sił, ale raczej będę tak robił, żeby za dużo w tym nie pisać xD. Co do FX to z importem problemu nie powinno być, bo już zależności w gradlu zrobiłem i intellij mi wykrywał FX'owe klasy także kodzik is ready for javafx

Jak zaczynałem pisać swinga to nie wiedziałem co to fx, więc można sformatować cokolowiek gdzie swing się pojawił

**Comment by wolski0420** [comment]
Zamykam, z tego co widzę to wszystko jest przeniesione na discussions
